MIN_SIMILARITY_THRESHOLD = 0.7
VEHICLE_COMPATIBILITY_BOOST = 0.08
VECTOR_SEARCH_LIMIT = 20
MAX_ALTERNATIVES = 3
MAX_UNMATCHED_CANDIDATES = 5
MIN_TOKEN_LENGTH_FOR_MATCH = 3
MIN_ALTERNATIVE_SIMILARITY_RATIO = 0.85
MAX_VEHICLE_SEARCH_TOKENS = 3