MIA_ADDITIONAL_NOTES_MAX_LENGTH: int = 5000

MIA_WORKFLOW_QUEUE = "mia_workflow"
MIA_DEAD_LETTER_EXCHANGE = "mia_dlx"
MIA_DEAD_LETTER_QUEUE = "mia_workflow_dlq"

WORKER_MAX_RETRIES = 3
WORKER_RETRY_HEADER = "x-retry-count"